preset_variants[folders.chess].push({
    name: "Chess5040",
    description: "The back rank of both players is randomized. Unlike Chess960, there is no restriction on bishop or king placement.",
	width: 8,
	height: 8,
	wins: [ends.royal_capture],
	draws: [ends.stalemate],
	next_turn_win: true,

	all_pieces: [
		{
			name: "Pawn",
			description: "Moves passively forward one step (or 2 on its first move), captures one step forward-diagonally, and promotes when reaching the back rank",
            sprite: "pawn",
            symbol: "p",
            notation: "",
			move: "i[0 -1 1 2]Bae+[0 -1 1 1]ae+([1 -1 1 1],[-1 -1 1 1])ca",
			promotions: [{white: 1, black: 0, to: [1, 2, 3, 4], on: [events.enter]}],
			attributes: [attrib.ep_captured, attrib.ep_capturer],
		},
		{
            name: "Rook",
            description: "Moves sideways and vertically as many spaces as it wants",
            sprite: "rook",
			symbol: "r",
			move: "[R]Ba",
			attributes: [attrib.castle_to],
		},
		{
            name: "Knight",
            description: "Jumps in a (2, 1) L-shaped pattern",
            sprite: "knight",
			symbol: "n",
			move: "[N]a",
		},
		{
            name: "Bishop",
            description: "Moves diagonally as many spaces as it wants",
            sprite: "bishop",
			symbol: "b",
			move: "[B]Ba",
		},
		{
            name: "Queen",
            description: "Moves like a Rook or Bishop",
            sprite: "queen",
			symbol: "q",
			move: "[Q]Ba",
		},
		{
            name: "King",
            description: "Moves one step in any direction. Can be checked and checkmated.",
            sprite: "king",
			symbol: "k",
			move: "[K]a+i[1 0 2 -1]BemP{Rook}",
			attributes: [attrib.royal, attrib.castle_from],
		},
	],
    setup: "br bn bb bq bk bb bn br 8bp",
    copy: "flip",
	zones: [
        "00000000 00000000 00000000 00000000 00000000 00000000 00000000 11111111",
        "11111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000",
	],
    fischer_zones: [0, 1],
});