preset_variants[folders.historical].push({
    name: "Courier Chess",
    description: "12th-century Chess variant. The added pieces are Mann, Elephant, Ferz, and Wazir. There is no castling.",
	width: 12,
	height: 8,
	wins: [ends.royal_capture],
	draws: [ends.stalemate],

	all_pieces: [
		{
			name: "Peasant",
			description: "Moves passively forward one step, captures one step forward-diagonally, and promotes to Ferz when reaching the back rank",
            sprite: "peasant",
            symbol: "p",
            notation: "",
			move: "[0 -1 1 1]ae+([1 -1 1 1],[-1 -1 1 1])ca",
            promotions: [{ white: 1, black: 0, to: ["F"], on: [events.enter] }],
		},
		{
            name: "Rook",
            description: "Moves sideways and vertically as many spaces as it wants",
            sprite: "rook",
			symbol: "R",
			move: "[R]Ba",
        },
        {
            name: "Knight",
            description: "Jumps in a (2, 1) L-shaped pattern",
            sprite: "knight",
            symbol: "N",
            move: "[N]a",
        },
        {
            name: "Elephant",
            description: "Jumps to the second diagonal",
            sprite: "elephant",
            symbol: "E",
            move: "[A]a",
        },
        {
            name: "Bishop",
            description: "Moves diagonally as many spaces as it wants",
            sprite: "bishop",
            symbol: "B",
            move: "[B]Ba",
        },
        {
            name: "Mann",
            description: "Non-Royal King",
            sprite: "commoner",
            symbol: "M",
            move: "[K]a",
        },
		{
            name: "Ferz",
            description: "Moves one step diagonally",
            sprite: "prince",
			symbol: "F",
			move: "[F]a",
        },
        {
            name: "King",
            description: "Moves one step in any direction. Can be checked and checkmated.",
            sprite: "king",
            symbol: "K",
            move: "[K]a",
            attributes: [attrib.royal],
        },
        {
            name: "Wazir",
            description: "Moves one step in any direction. Can be checked and checkmated.",
            sprite: "fortress",
            symbol: "W",
            move: "[W]a",
        },
	],
    setup: "bR bN bE bB bM bK bF bW bB bE bN bR 12bp",
    copy: "flip",zones: [
		"000000000000 000000000000 000000000000 000000000000 000000000000 000000000000 000000000000 111111111111",
		"111111111111 000000000000 000000000000 000000000000 000000000000 000000000000 000000000000 000000000000",
	],
});