preset_variants[2].push({
    name: "Courier Chess (starting moves)",
    description: "12th-century Chess variant. The added pieces are Mann, Elephant, Ferz, and Wazir. There is no castling. The first 4 moves are forced to be the traditional starting moves.",
	width: 12,
	height: 8,
	wins: [ends.royal_capture],
    draws: [ends.stalemate],

    all_pieces: [
        {
            name: "Peasant",
            description: "Moves passively forward one step, captures one step forward-diagonally, and promotes to Ferz when reaching the back rank",
            sprite: "peasant",
            symbol: "p",
            notation: "",
            move: "T{4}[0 -1 1 1]ae+T{4}([1 -1 1 1],[-1 -1 1 1])ca",
            promotions: [{ white: 1, black: 0, to: ["F"], on: [events.enter] }],
        },
        {
            name: "Peasant2",
            description: "Moves passively forward one step, captures one step forward-diagonally, and promotes to Ferz when reaching the back rank",
            sprite: "peasant",
            symbol: "2",
            notation: "",
            move: "it{5}[0 -2 1 1]a+T{4}[0 -1 1 1]ae+T{4}([1 -1 1 1],[-1 -1 1 1])ca",
            promotions: [{ white: 1, black: 0, to: ["F"], on: [events.enter] }],
        },
		{
            name: "Rook",
            description: "Moves sideways and vertically as many spaces as it wants",
            sprite: "rook",
			symbol: "R",
            move: "T{4}[R]Ba",
        },
        {
            name: "Knight",
            description: "Jumps in a (2, 1) L-shaped pattern",
            sprite: "knight",
            symbol: "N",
            move: "T{4}[N]a",
        },
        {
            name: "Elephant",
            description: "Jumps to the second diagonal",
            sprite: "elephant",
            symbol: "E",
            move: "T{4}[A]a",
        },
        {
            name: "Bishop",
            description: "Moves diagonally as many spaces as it wants",
            sprite: "bishop",
            symbol: "B",
            move: "T{4}[B]Ba",
        },
        {
            name: "Mann",
            description: "Non-Royal King",
            sprite: "commoner",
            symbol: "M",
            move: "T{4}[K]a",
        },
		{
            name: "Ferz",
            description: "Moves one step diagonally",
            sprite: "prince",
			symbol: "F",
			move: "it{5}[0 -2 1 1]a+T{4}[F]a",
        },
        {
            name: "King",
            description: "Moves one step in any direction. Can be checked and checkmated.",
            sprite: "king",
            symbol: "K",
            move: "T{4}[K]a",
            attributes: [attrib.royal],
        },
        {
            name: "Wazir",
            description: "Moves one step in any direction. Can be checked and checkmated.",
            sprite: "fortress",
            symbol: "W",
            move: "T{4}[W]a",
        },
	],
    setup: "bR bN bE bB bM bK bF bW bB bE bN bR b2 5bp b2 4bp b2",
    copy: "flip",zones: [
		"000000000000 000000000000 000000000000 000000000000 000000000000 000000000000 000000000000 111111111111",
		"111111111111 000000000000 000000000000 000000000000 000000000000 000000000000 000000000000 000000000000",
	],
});