preset_variants[folders.ccit].push({
    name: "Omega Chess Extreme",
	author: "Ristet",
    description: "Omega Chess but with Advanced stuff and a bit more!",
	style: "checkered",
	width: 12,
	height: 12,
	wins: [ends.royal_capture, ends.stalemate],

	all_pieces: [
		{
			name: "Pawn Rabbit",
			description: "Moves passively forward one step (or 2 or 3 on its first move), captures one step forward-diagonally, and promotes when reaching the back rank",
            sprite: "pawn",
            symbol: "p",
            notation: "",
			move: "i[0 1 1 3]Bae+[S]ae+[P]ca",
            promotions: {white: "black_rank_2", black: "white_rank_2", to: "NRNS"},
			attributes: [attrib.ep_capturer, attrib.ep_captured],
		},
		{
            name: "Rook",
            description: "Moves sideways and vertically as many spaces as it wants",
            sprite: "rook",
			symbol: "R",
			move: "[R]Ba",
			attributes: [attrib.castle_to],
		},
		{
            name: "Knighty",
            description: "Moves like a Knight but can passively move like a Zebra",
            sprite: "knight",
			symbol: "N",
			move: "[N]a+[Z]ae",
		},
		{
            name: "Bishop",
            description: "Moves diagonally as many spaces as it wants",
            sprite: "bishop",
			symbol: "B",
			move: "[B]Ba",
		},
		{
            name: "Castling Queen",
            description: "Queen but it can castle like a King",
            sprite: "queen",
			symbol: "Q",
			move: "[Q]Ba+i[1 0 2 -1]BemP{Rook}",
			attributes: [attrib.castle_from]
		},
		{
            name: "King",
            description: "Moves one step in any direction. Can be checked and checkmated.",
            sprite: "king",
			symbol: "K",
            move: "[K]a+i[1 0 2 -1]BemP{Rook}",
			attributes: [attrib.royal, attrib.castle_from],
		},
		{
            name: "Swapper",
            description: "Moves like a Queen, swaps with enemies instead of capturing them",
            sprite: "pylon",
			symbol: "S",
            move: "z{0 0}[Q]Ba+[S]a",
			attributes: [attrib.save_enemy, attrib.dont_flip_enemy],
		},
		{
            name: "Jester",
            description: "Copies the last moved piece AND immobolizes enemies",
            sprite: "jester",
			symbol: "J",
            move: "[K]a",
			attributes: [attrib.copy_move, attrib.copy_attrib, attrib.glue_curse, attrib.peace_curse],
			held_move: "[K]",
		},
		{
            name: "Jester Start",
            description: "Copies the last moved piece AND immobolizes enemies",
            sprite: "jester",
			symbol: "j",
			notation: "J",
            move: "[S]a",
			promotions: {to: "J", white: "white_rank_2", black: "black_rank_2"},
		},
		{
            name: "Kamikaze",
            description: "Moves like a King or Knight but it and its capturer/captured will be removed",
            sprite: "potion",
			symbol: "Z",
            move: "z{0 0}([K],[N])a+[S]a",
			attributes: [attrib.bomb, attrib.fireball],
		},
		{
            name: "Omega Wizard",
            description: "Moves like a Giraffe(Camel) or a Ferz",
            sprite: "sorcerer",
			symbol: "W",
            move: "([F],[C])a",
		},
		{
            name: "Omega Champion",
            description: "Moves like a Crow(Dabbabah), Dog(Wazir), or an Alfil",
            sprite: "guardian",
			symbol: "G",
            move: "([W],[D],[A])a",
		},

	],
    setup: "bW 3. bZ bS bj bZ 3. bW . bG bR bN bB bQ bK bB bN bR bG 2. 10bp",
    copy: "flip",
	active_squares: "100000000001 011111111110 011111111110 011111111110 011111111110 011111111110 011111111110 011111111110 011111111110 011111111110 011111111110 100000000001",
	zones: [
		"100000000001 011111111110 011111111110 011111111110 011111111110 011111111110 011111111110 011111111110 011111111110 011111111110 011111111110 100000000001"
	],
});